# Generated by Django 2.2.5 on 2021-11-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereviews',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='moviereviews',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='create_at',
        ),
    ]
